### ISSUE TITLE
The app is closing every time i open it

### ISSUE THREAD

**Issue by Yetielcodificador** [OmegaDevStudio/Mass-Token-Online#1]
i thinked it was that `signal`  of python was not installed so i recurred to install but it fails and gives this error:
ERROR: Could not find a version that satisfies the requirement signal (from versions: none)

ERROR: No matching distribution found for signal
how to fix it??

**Comment by Shell1010** [comment]
Okay my code doesn't use anything called signal. Post full error logs.

**Comment by Yetielcodificador** [comment]
is this EvilToken? or was removed?

**Comment by Shell1010** [comment]
What are you even saying? Read the script this repository is associated with.

**Comment by Shell1010** [comment]
Join https://discord.gg/TbtnTRDt if you're still having issues
